//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT4_TTCD1_PhamThiThuHuyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Product
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public string image { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceSale { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public string SeoKeyword { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifedDate { get; set; }
        public string ModiferBy { get; set; }
    }
}
