//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT4_TTCD1_PhamThiThuHuyen.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Adv> tb_Adv { get; set; }
        public virtual DbSet<tb_Category> tb_Category { get; set; }
        public virtual DbSet<tb_Contact> tb_Contact { get; set; }
        public virtual DbSet<tb_Order> tb_Order { get; set; }
        public virtual DbSet<tb_OrderDetail> tb_OrderDetail { get; set; }
        public virtual DbSet<tb_Post> tb_Post { get; set; }
        public virtual DbSet<tb_Product> tb_Product { get; set; }
        public virtual DbSet<tb_ProductCategory> tb_ProductCategory { get; set; }
        public virtual DbSet<tb_Subscribe> tb_Subscribe { get; set; }
        public virtual DbSet<User> Users { get; set; }

        public System.Data.Entity.DbSet<K22CNT4_TTCD1_PhamThiThuHuyen.Models.News> News { get; set; }

        public System.Data.Entity.DbSet<K22CNT4_TTCD1_PhamThiThuHuyen.Models.Posts> Posts { get; set; }

        public System.Data.Entity.DbSet<K22CNT4_TTCD1_PhamThiThuHuyen.Models.ProductCategory> ProductCategories { get; set; }

        public System.Data.Entity.DbSet<K22CNT4_TTCD1_PhamThiThuHuyen.Models.Category> Categories { get; set; }
    }
}
